### ISSUE TITLE
Get DesFire keys

### ISSUE THREAD

**Issue by osysltd** [dev-zzo/ChameleonMini#17]
Hi Dima!

Thank you very much for the development and efforts. What do you think, would it be possible to extract desfire authentication key from the reader authentication attempt (reader attack) emulating desfire card by the device?

**Comment by dev-zzo** [comment]
Hey there. The authentication scheme in use is basically like this:

1. The card sends Ek(CardNonce)
2. The reader sends Dk(ReaderNonce|CardNonce)
3. The card sends E(ReaderNonce)

Currently, trying to crack this scheme only by the known plain text attack is equivalent to brute force search for the AES-128 key given the correct plaintext-ciphertext pair and as such is not feasible. Depending on the reader, you will have a better chance attacking the reader device itself. Let me know if you'd like to discuss that option off the list. :-)

**Comment by osysltd** [comment]
Sorry if I didn't get you or DesFire authentication mechanism correctly, but aren't we able to get the key by which reader is trying to authenticate?

**Comment by dev-zzo** [comment]
Explain your idea! :-)

**Comment by lvandenb** [comment]
No, to my knowledge keys are never sent during normal usage. Only when creating / changing card and applications

**Comment by osysltd** [comment]
Please could you can share some specific document describing this? All I can find is a statement that [reader tries to authenticate with key for PICC Application](https://ridrix.wordpress.com/tag/desfire-authentication/):

```
--> 0a 00
<-- af a2 be cd 03 d8 46 cb 33
--> af b0 cc bc ed 8f c8 38 c9 08 dc e2 4d 86 ca ec 3c
<-- 00 76 73 d9 49 71 3f f2 d1
```

**Comment by dev-zzo** [comment]
"Philips Semiconductors. Product Specification Rev. 3.1 April 2004" I am sure you will figure it out. ;-)
