### ISSUE TITLE
desfire: debug output in iso-activation breaks the timing

### ISSUE THREAD

**Issue by shombre** [dev-zzo/ChameleonMini#2]
first of all: great job!

now to the issue: 
with debug output enabled my reader always reports timeout during activation according to iso14443.
with debug output disabled (`//#define DEBUG_THIS`) activation works fine!
not a big issue, but maybe good to know..  : )

tested with nxp pegoda reader

**Comment by dev-zzo** [comment]
xD makes sense. the debug output is better left disabled in "production" builds. I think it's best to employ the logging facilities to collect traces, which I should do at some point.

**Comment by dev-zzo** [comment]
I believe all the interfering output has been removed in commit c40b9c5c.
