### ISSUE TITLE
Question: current status?

### ISSUE THREAD

**Issue by Reventl0v** [dev-zzo/ChameleonMini#21]
Hi,
I'm wondering what is covered by this project, right now?

I'm searching for a way to « clone » a mifare desfire or mifare desfire uid onto a chameleon mini, and i'm wondering if this is possible (with the good atqa, sak, ats and uid).

Thanks!

**Comment by dev-zzo** [comment]
Right, so this is semi-working for EV0 cards, and even then, the ATR bytes are not really correct because ChaMini doesn't support anything above the 106kbit/s speed. Emulation is super limited.

To clone a card, you will need the actual keys (at least for read access), otherwise there is nothing much you can do -- the card won't work with whatever system you have if it actually uses DESFire features and not just the card's UID. Then, if you have the keys, you might as well program a real card, omitting all the lockdown steps so you can wipe it clean afterwards. :-)

We can discuss your situation in more detail if you want.

Cheers!

**Comment by Reventl0v** [comment]
Thank you for this quick answer!

I'm not trying to really « clone » a card, I just want to use « uid emulation » (cards are using desfire features, but not for the scenario I want to test).

The problem with using « real cards » is the fact I cannot change the UID, and in my case the whole scenario I want to test relies on UIDs.

About the ATR bytes, i'm not sure they're really used, but for that I'd need to check if with the good atqa, uid, and sak bytes, i'm rightly authenticated.

Tha

**Comment by dev-zzo** [comment]
AFAIK the emulation should work if you want to use the UID only. Give it a try and let me know the results. :-)

**Comment by herrmanns** [comment]
hello, just a little question. how can i tell chamelon to use a atqa 03 44 sak 20 and ats ?
when i check the config? i dont see any desfire support. not sure if i have the right firmware. hopefully somebody could help a little as i am a "beginner"
thanks a lot!

**Comment by herrmanns** [comment]
can anybody upload the compiled firmware files somewhere (dropbox?)? i am not able to compile it by myself. please

**Comment by gtpy** [comment]
Which OS are your using?
Windows, Linux?
Maybe I can help you to compile it.

**Comment by dev-zzo** [comment]
@herrmanns Please make sure you have checked out the desfire branch of this repo. The master branch here doesn't have the code and just follows the upstream.

**Comment by herrmanns** [comment]
sorry i am late ;)
i got it managed (surprisingly). i ve never worked with cygwin etc. but thank you very much for the offer to help.btwi am looking for some code for chameleon mini rev g which increase/decrease the second and third byte of a 7byte uid mifare classic card.there is a random generator and also increse/decrease the first and last byte but no option for "custom" byte in the row.are you possibly able to modify the code for to define which byte should be in/decreased?
cheers and thank you very much
herrmann
(btw i wasnt able to activate the reader in desfire sim mode) 

Gesendet von Yahoo Mail für iPhone


Am Dienstag, Dezember 5, 2017, 9:31 AM schrieb init0 <notifications@github.com>:


Which OS are your using?
Windows, Linux?
Maybe I can help you to compile it.

**Comment by herrmanns** [comment]
sorry i am late dmitry ;)
i got it managed to get the firmware compiled with desfire support.but  i wasnt able to activate the reader in desfire sim mode. it was just quiet and didnt recogised anything. maybe there is something wrong. acr reader just spits error unknown card but it can read desfire.

btwi am looking for some code for chameleon mini rev g which increase/decrease the second and third byte of a 7byte uid mifare classic card.there is a random generator and also increse/decrease the first and last byte but no option for "custom" byte in the row.are you possibly able to modify the code for to define which byte should be in/decreased?
cheers and thank you very much
herrmann


Gesendet von Yahoo Mail für iPhone


Am Dienstag, Dezember 5, 2017, 10:17 AM schrieb Dmitry Janushkevich <notifications@github.com>:


@herrmanns Please make sure you have checked out the desfire branch of this repo. The master branch here doesn't have the code and just follows the upstream.

**Comment by herrmanns** [comment]
sry.. my fault. compiling was successful. thanks to the community!

**Comment by dev-zzo** [comment]
No worries. :-) closing this, then.
