### ISSUE TITLE
Question: Help for compiling 

### ISSUE THREAD

**Issue by gtpy** [dev-zzo/ChameleonMini#22]
Hi,
I am really new to GitHub.
Now get my chameleon and also want to test your DESFire  #functionality.
Need I to compile it from your DESFire branch?

Thanks for your support.

**Comment by gtpy** [comment]
Ok. Get it working. Used Ubuntu 17.10 and Kali.
Later flashed via Win10.
Found no way to flash under Linux.
Later you get some Info Tests about tests with MF_DESFire EV1 
Closed.

**Comment by DE-Christian** [comment]
Hi gtpy,
I have the same problem. Could you please write a little bit more details how you have compiled it ?
I hope it’s OK that I have add this comment here.

**Comment by gtpy** [comment]
@DE-Christian No problem. I'll add more instructions later whem i am home.
I think you are from Germany: please mail me under csf2@protonmail.ch - is much easier to describe it in German. Later I'll add this here for the community.

**Comment by gtpy** [comment]
Problem from DE-Christian was:

OS: Ubuntu 17.10

> test@test-virtual-machine:~/Downloads/ChameleonMini-master/Firmware/Chameleon-Mini$ make
>
> **..shorten up the message..**
>
> In file included from Chameleon-Mini.c:1:0:
>
> Chameleon-Mini.h:4:20: fatal error: avr/io.h: No such file or directory
>
> compilation terminated.
>
> ../LUFA/Build/lufa_build.mk:294: recipe for target 'Bin/Chameleon-Mini.o' failed
>
> make: *** [Bin/Chameleon-Mini.o] Error 1
>
> test@test-virtual-machine:~/Downloads/ChameleonMini-master/Firmware/Chameleon-Mini$

Installed packets was: `avra + avrdude + make + git + gcc-avr`

Solution: Install missing packet `avr-libc`
