### ISSUE TITLE
desfire: authentication not working

### ISSUE THREAD

**Issue by shombre** [dev-zzo/ChameleonMini#3]
always run into `STATUS_AUTHENTICATION_ERROR` (line 701).
someone else tried it?

from a short code review i guess that the IV from the CBC cipher is not handled correct.
from my understanding it should be reset at start and end of the authentication process, not with every call of the cipher function.

**Comment by shombre** [comment]
May have mixed it up with the ev1 stuff, don't know if D40/ev0 uses CBC at all.
Anyway did not make it work yet.

**Comment by dev-zzo** [comment]
@shombre if you're testing the code -- could you please make sure TDEA implementation is correct? I am not sure I've implemented it properly, although I followed along the Atmel reference implementation.

To my best knowledge, EV0 does use CBC.

**Comment by dev-zzo** [comment]
hmmm, I better just implement built-in self test for this.

**Comment by dev-zzo** [comment]
OK, TDEA implementation seems to be broken. Will debug and see what's wrong with it.

**Comment by dev-zzo** [comment]
@shombre I've implemented a small self-test, which seems to pass fine. Also fixed a stupid error (byte count vs block count). Looking further into this...

**Comment by dev-zzo** [comment]
@shombre Please record the trace of a failed auth. Before presenting the card, use `LOGMODE=MEMORY` to start logging the data, then use `LOGDOWNLOAD` to get it from the card to your box. Use `chamlog` to read the trace. This can provide the insight needed to fix things! Thanks :-)

**Comment by shombre** [comment]
@dev-zzo There you are:

key = 97CB6532994C2693C9643299CC663319
```
46290 ms <+46290 ms>:CODEC RX         (1   bytes) [26]
46290 ms <    +0 ms>:CODEC TX         (2   bytes) [4403]
46295 ms <    +5 ms>:CODEC RX         (2   bytes) [9320]
46295 ms <    +0 ms>:CODEC TX         (5   bytes) [8811223388]
46301 ms <    +6 ms>:CODEC RX         (9   bytes) [93708811223388faf4]
46301 ms <    +0 ms>:CODEC TX         (3   bytes) [24d836]
46306 ms <    +5 ms>:CODEC RX         (2   bytes) [9520]
46306 ms <    +0 ms>:CODEC TX         (5   bytes) [4455667700]
46312 ms <    +6 ms>:CODEC RX         (9   bytes) [957044556677007ab8]
46312 ms <    +0 ms>:CODEC TX         (3   bytes) [20fc70]
47904 ms < +1592 ms>:CODEC RX         (4   bytes) [e0803173]
47904 ms <    +0 ms>:CODEC TX         (8   bytes) [0675008102006e79]
54785 ms < +6881 ms>:CODEC RX         (6   bytes) [0a000a00de77]
54785 ms <    +0 ms>:CODEC TX         (13  bytes) [0a00af4b8bb034121c5566fa92]
54795 ms <   +10 ms>:CODEC RX         (21  bytes) [0b00af9c862f42e0c44cefea81cd807da0638e1869]
54795 ms <    +0 ms>:CODEC TX         (5   bytes) [0b00aec6c0]
```
```
35697 ms <+46438 ms>:CODEC RX         (1   bytes) [26]
35697 ms <    +0 ms>:CODEC TX         (2   bytes) [4403]
35703 ms <    +6 ms>:CODEC RX         (2   bytes) [9320]
35703 ms <    +0 ms>:CODEC TX         (5   bytes) [8811223388]
35709 ms <    +6 ms>:CODEC RX         (9   bytes) [93708811223388faf4]
35709 ms <    +0 ms>:CODEC TX         (3   bytes) [24d836]
35715 ms <    +6 ms>:CODEC RX         (2   bytes) [9520]
35715 ms <    +0 ms>:CODEC TX         (5   bytes) [4455667700]
35721 ms <    +6 ms>:CODEC RX         (9   bytes) [957044556677007ab8]
35721 ms <    +0 ms>:CODEC TX         (3   bytes) [20fc70]
36719 ms <  +998 ms>:CODEC RX         (4   bytes) [e0803173]
36719 ms <    +0 ms>:CODEC TX         (8   bytes) [0675008102006e79]
38826 ms < +2107 ms>:CODEC RX         (6   bytes) [0a000a00de77]
38826 ms <    +0 ms>:CODEC TX         (13  bytes) [0a00afdb1d31786dd75979b454]
38840 ms <   +14 ms>:CODEC RX         (21  bytes) [0b00af16a254a867456ee2d67feb060e006816a373]
38840 ms <    +0 ms>:CODEC TX         (5   bytes) [0b00aec6c0]
```

key = 00000000000000000000000000000000
```
36963 ms <+36963 ms>:CODEC RX         (1   bytes) [26]
36963 ms <    +0 ms>:CODEC TX         (2   bytes) [4403]
36968 ms <    +5 ms>:CODEC RX         (2   bytes) [9320]
36968 ms <    +0 ms>:CODEC TX         (5   bytes) [8811223388]
36974 ms <    +6 ms>:CODEC RX         (9   bytes) [93708811223388faf4]
36974 ms <    +0 ms>:CODEC TX         (3   bytes) [24d836]
36980 ms <    +6 ms>:CODEC RX         (2   bytes) [9520]
36980 ms <    +0 ms>:CODEC TX         (5   bytes) [4455667700]
36986 ms <    +6 ms>:CODEC RX         (9   bytes) [957044556677007ab8]
36986 ms <    +0 ms>:CODEC TX         (3   bytes) [20fc70]
38911 ms < +1925 ms>:CODEC RX         (4   bytes) [e0803173]
38911 ms <    +0 ms>:CODEC TX         (8   bytes) [0675008102006e79]
45061 ms < +6150 ms>:CODEC RX         (6   bytes) [0a000a00de77]
45061 ms <    +0 ms>:CODEC TX         (13  bytes) [0a00afdfeb4933ec1f16821e9e]
45069 ms <    +8 ms>:CODEC RX         (21  bytes) [0b00af1d3c30149548afe50023b3f86806825b7db3]
45069 ms <    +0 ms>:CODEC TX         (5   bytes) [0b00aec6c0]
```
```
53489 ms < +8420 ms>:CODEC RX         (1   bytes) [26]
53489 ms <    +0 ms>:CODEC TX         (2   bytes) [4403]
53494 ms <    +5 ms>:CODEC RX         (2   bytes) [9320]
53494 ms <    +0 ms>:CODEC TX         (5   bytes) [8811223388]
53500 ms <    +6 ms>:CODEC RX         (9   bytes) [93708811223388faf4]
53500 ms <    +0 ms>:CODEC TX         (3   bytes) [24d836]
53506 ms <    +6 ms>:CODEC RX         (2   bytes) [9520]
53506 ms <    +0 ms>:CODEC TX         (5   bytes) [4455667700]
53512 ms <    +6 ms>:CODEC RX         (9   bytes) [957044556677007ab8]
53512 ms <    +0 ms>:CODEC TX         (3   bytes) [20fc70]
55205 ms < +1693 ms>:CODEC RX         (4   bytes) [e0803173]
55205 ms <    +0 ms>:CODEC TX         (8   bytes) [0675008102006e79]
59829 ms < +4624 ms>:CODEC RX         (6   bytes) [0a000a00de77]
59830 ms <    +1 ms>:CODEC TX         (13  bytes) [0a00af273b6917f99562e765bd]
59837 ms <    +7 ms>:CODEC RX         (21  bytes) [0b00af730ba4bf67e166361c270aee3820a7b5f93b]
59837 ms <    +0 ms>:CODEC TX         (5   bytes) [0b00aec6c0]
```

btw: 872375d5ae8af15619212d95c2f06f442db30e45 prevents the chameleon from working:
- when calling `RunTDEATests()` in `MifareDesfireAppInit(void)` my terminal can not find the comport anymore
- `MifareDesfireAppReset(void)` does not initialize the 14443 stuff

**Comment by dev-zzo** [comment]
@shombre Please see if things are better now wrt hangs/crashes. The code was broken for some time -- I forgot to push yesterday. :D I've improved things in `AppReset()` a bit.

**Comment by dev-zzo** [comment]
With commit c3ae7d5, you will now have nonce B always set to a fixed value, both the key and the nonce logged on auth step 1, and received nonce A and B' logged at auth step 2. This should finally shed some light on what's wrong here. I've also updated log parser to decode those log entries.

**Comment by shombre** [comment]
I will be home late tonight ..  will make a new log tomorrow

**Comment by dev-zzo** [comment]
OK, the auth code is broken anyway, no need to test. :-(

* From all the sources I have on hands, it seems to emerge that the designers had their own very... unusual interpretation of CBC. Even though they use only encryption operation, they change the chaining modes as appropriate. This is not taken into account by my code.
* Another thing was use of the IV values for CBC. Have to keep the IV between the two stages and make use of it when handling data. At the moment, I am not sure whether this spans across commands.

Will have to fix things next week... I've made IV input explicit to the encipherment routine, now need to make another one for the second CBC mode.

**Comment by dev-zzo** [comment]
Bah... implemented that today. From the dumps that I had access to, apparently, during authentication CBC is used only when PCD sends / PICC receives RndA|RndB. In other cases, plain TDEA is used, with no effect on the IV. Please do test the new code and with any luck, it will work...

Source: https://ridrix.wordpress.com/2009/09/19/mifare-desfire-communication-example/

**Comment by shombre** [comment]
here a new log with the latest version:
```
63401 ms <+63401 ms>:CODEC RX         (1   bytes) [26]
63401 ms <    +0 ms>:CODEC TX         (2   bytes) [4403]
63406 ms <    +5 ms>:CODEC RX         (2   bytes) [9320]
63406 ms <    +0 ms>:CODEC TX         (5   bytes) [8811223388]
63416 ms <   +10 ms>:CODEC RX         (9   bytes) [93708811223388faf4]
63416 ms <    +0 ms>:CODEC TX         (3   bytes) [24d836]
63422 ms <    +6 ms>:CODEC RX         (2   bytes) [9520]
63422 ms <    +0 ms>:CODEC TX         (5   bytes) [4455667700]
63428 ms <    +6 ms>:CODEC RX         (9   bytes) [957044556677007ab8]
63428 ms <    +0 ms>:CODEC TX         (3   bytes) [20fc70]
64993 ms < +1565 ms>:CODEC RX         (4   bytes) [e0803173]
64993 ms <    +0 ms>:CODEC TX         (8   bytes) [0675008102006e79]
03798 ms < +4341 ms>:CODEC RX         (6   bytes) [0a000a00de77]
03798 ms <    +0 ms>:APP AUTH KEY     (16  bytes) [97cb6532994c2693c9643299cc663319]
03798 ms <    +0 ms>:APP NONCE B      (8   bytes) [3300000000000000]
03798 ms <    +0 ms>:CODEC TX         (13  bytes) [0a00af087ac4ea01f861661363]
03806 ms <    +8 ms>:CODEC RX         (21  bytes) [0b00af9b14b745b9cb33956a2f586a9e271742a83e]
03806 ms <    +0 ms>:APP NONCE AB     (16  bytes) [31ebf2f019187e7ae2ede759fea0e6ac]
03806 ms <    +0 ms>:CODEC TX         (5   bytes) [0b00aec6c0]
```

**Comment by dev-zzo** [comment]
Thanks!

Apart from the RndB not being what I expected it to be (lol, forgot to change indices properly, but that doesn't have any impact in fact), I can see that it is being transmitted to the reader as expected (if I run TDEA decryption with the key given in the log on the value being TX'd, it compares correctly).

What the card gets back from the reader, though, seems to suggest there might be a problem with the keys; both I and the card can't decrypt the PCD's answer to get the correct value for nonce B, as you can see in the reported nonce AB entry -- it should contain the reader's nonce A and the card's nonce B shifted by one byte, but that's not the case here.

Could you please check the key is set correctly in both the card and the reader?

**Comment by dev-zzo** [comment]
Verification steps:
Let the reader's nonce be A, the card nonce be B.
The reader sends: C1|C2, where C1 = D(A) and C2 = D(B' ^ C1) according to the CBC rules.
Then, we manually compute E(C2) = E(D(B' ^ C1)) = B' ^ C1, and thus can easily obtain B' = E(C2) ^ C1, which should be the same as the card's B but rotated by one byte. Note this does not depend on whatever IV was used before we started the transmission.

**Comment by shombre** [comment]
My reader uses key `97CB6532994C2693C9643299CC663319` which matches to the key in the log.
btw: is there a reason that this is the default key currently?

Analysing is difficult as long as we don't know the reader's nonce A. Unfortunately I currently don't have a setup where i can do this.

**Comment by dev-zzo** [comment]
As for the key, I believe the card has the key set to all zeros when wiped and formatted (happens on every FW upgrade). I am not entirely sure how you've managed to set the new master key w/o authenticating first. :-) Or, there may be something terribly wrong with the way keys are managed here...

For the second point, currently we don't need the nonce A as computations for nonce B do not depend on it; you can see that from the above.

**Comment by dev-zzo** [comment]
In d3844d4, I've made master key wiping explicit... not sure whether it helps as it should be set implicitly to zeros due to the way storage blocks are allocated. But never hurts to be explicit.

**Comment by dev-zzo** [comment]
Right, found a subtle bug in init code... f4a8077 shows how dumb errors are sometimes.

**Comment by shombre** [comment]
I confirm: default key is `00000000000000000000000000000000` now.

**Comment by dev-zzo** [comment]
Great. We're one bug closer to getting things working now...

**Comment by dev-zzo** [comment]
@shombre Could you please test the latest code? It seems we've reached understanding on how things are supposed to work in emsec's issue.

**Comment by shombre** [comment]
```
01458 ms <+14273 ms>:CODEC RX         (6   bytes) [0a000a00de77]
01458 ms <    +0 ms>:APP AUTH KEY     (16  bytes) [00000000000000000000000000000000]
01458 ms <    +0 ms>:APP NONCE B      (8   bytes) [cafebabe00112233]
01458 ms <    +0 ms>:CODEC TX         (13  bytes) [0a00afee91301ee8f584d6dec0]
01471 ms <   +13 ms>:CODEC RX         (21  bytes) [0b00affaf3e6918a55feb2dc470aa441a8181b0a1e]
01471 ms <    +0 ms>:APP AUTH KEY     (16  bytes) [00000000000000000000000000000000]
01471 ms <    +0 ms>:APP NONCE AB     (16  bytes) [d916b9d61a61082e044958919b77cd78]
01471 ms <    +0 ms>:CODEC TX         (5   bytes) [0b00aec6c0]
```

**Comment by shombre** [comment]
as you see nonce B is still not correct.

but (maybe only because of the 00..00 key) when you run a "normal" des-cbc decipher on the crypted nonce AB', you see 2 thing:
- nonce A is deciphered correct already
- nonce B' is correct after "normal" des-cbc decipher

here is a link to an online tool with the data from above:
http://des.online-domain-tools.com/run/?inputType=frm-text&text=faf3e6918a55feb2dc470aa441a8181b&text_type=hex&function=des&mode=cbc&key=0000000000000000&key_type=hex&iv=00%2000%2000%2000%2000%2000%2000%2000&do=form-submit&decrypt=do

seems that there still is a problem with the IV handing whithi this 2 block length deciphering.

**Comment by shombre** [comment]
done the same with "non-zero" keys. both do not decipher correct with this "normal" des-cbc decipher. This should be due to this "desfire-mode" des-cbc deciphering mentioned in the link you posted above.

DES:
```
33896 ms <+52981 ms>:CODEC RX         (6   bytes) [0a000a00de77]
33896 ms <    +0 ms>:APP AUTH KEY     (16  bytes) [11111111111111111111111111111111]
33896 ms <    +0 ms>:APP NONCE B      (8   bytes) [cafebabe00112233]
33896 ms <    +0 ms>:CODEC TX         (13  bytes) [0a00afc884f86a75717356f88f]
33909 ms <   +13 ms>:CODEC RX         (21  bytes) [0b00af225521ad58064807647936023726809f47b4]
33910 ms <    +1 ms>:APP AUTH KEY     (16  bytes) [11111111111111111111111111111111]
33910 ms <    +0 ms>:APP NONCE AB     (16  bytes) [cd2c412fd2a13657dcef9fad49247bcd]
33910 ms <    +0 ms>:CODEC TX         (5   bytes) [0b00aec6c0]
```

2kTDES:
```
46304 ms < +8947 ms>:CODEC RX         (6   bytes) [0a000a00de77]
46304 ms <    +0 ms>:APP AUTH KEY     (16  bytes) [11111111111111112211111111111111]
46304 ms <    +0 ms>:APP NONCE B      (8   bytes) [cafebabe00112233]
46304 ms <    +0 ms>:CODEC TX         (13  bytes) [0a00af1cd3c4c3605705eb7026]
46319 ms <   +15 ms>:CODEC RX         (21  bytes) [0b00af3f0cc6db74e469081b68176af1b38e6b24e4]
46319 ms <    +0 ms>:APP AUTH KEY     (16  bytes) [11111111111111112211111111111111]
46319 ms <    +0 ms>:APP NONCE AB     (16  bytes) [cda27cdeb56b3dd9c1b678db65c65ac2]
46319 ms <    +0 ms>:CODEC TX         (5   bytes) [0b00aec6c0]
```

**Comment by dev-zzo** [comment]
OK, I see the problem, I think. In legacy auth mode, the PICC performs enciphering operation on the received data, always. So, in ECB mode (no chaining), E(225521ad58064807647936023726809f) = cd2c412fd2a13657dcef9fad49247bcd. Which is exactly what the card shows us in the log. Then, if I perform the "CBC receive" chaining manually: DCEF9FAD49247BCD ^ 225521AD58064807 = FEBABE00112233CA, which is RndB'!!! This means that my code does ECB due to whatever reason and not CBC. And this is the only issue we have at hand. Will be fixing that today.

**Comment by shombre** [comment]
Sounds plausible!

When you are reworking the encryption, let me make a proposal for the implementation:
I would find it easier for readability and reuseability if the assembler part only performs enciphering (later also deciphering) in ECB / single block mode. Then call it in a C module that handles the IV to make it a CBC.
If then the ASM code is also capable of handling 3KTDES, we are on a perfect way to reuse this for i.e. EV1-DES-auth and others.

**Comment by dev-zzo** [comment]
Your concerns here are quite valid. But I fear that leaving only e.g. TDEA basic routine in assembly and implementing CBC in C will incur considerable overhead due to unnecessary moves of data between registers and memory. But I can assure you that the code is reusable for other TDEA based tasks like ISO auth, both 2-key and 3-key.

With commit a43a018, I believe things should be in order.

**Comment by shombre** [comment]
```
07357 ms < +3608 ms>:CODEC RX         (6   bytes) [0a000a00de77]
07357 ms <    +0 ms>:APP AUTH KEY     (16  bytes) [00000000000000000000000000000000]
07357 ms <    +0 ms>:APP NONCE B      (8   bytes) [cafebabe00112233]
07357 ms <    +0 ms>:CODEC TX         (13  bytes) [0a00afee91301ee8f584d6dec0]
07365 ms <    +8 ms>:CODEC RX         (21  bytes) [0b00af2f6d6f52f6da0adc2e0dfd3c642efe890793]
07365 ms <    +0 ms>:APP AUTH KEY     (16  bytes) [00000000000000000000000000000000]
07365 ms <    +0 ms>:APP NONCE AB     (16  bytes) [1de9357d45899653d1d7d152e7f83916]
07365 ms <    +0 ms>:CODEC TX         (5   bytes) [0b00aec6c0]
```

**Comment by dev-zzo** [comment]
T_T
Why oh why I can't get this right.
Found two bugs; please see if commit 62b4166 gets it right. Thanks for your help!

**Comment by shombre** [comment]
```
21371 ms < +6420 ms>:CODEC RX         (6   bytes) [0a000a00de77]
21371 ms <    +0 ms>:APP AUTH KEY     (16  bytes) [00000000000000000000000000000000]
21371 ms <    +0 ms>:APP NONCE B      (8   bytes) [cafebabe00112233]
21371 ms <    +0 ms>:CODEC TX         (13  bytes) [0a00afee91301ee8f584d6dec0]
21381 ms <   +10 ms>:CODEC RX         (21  bytes) [0b00af05b0d77e3dbb5920ba42198acb3679a912b0]
21381 ms <    +0 ms>:APP AUTH KEY     (16  bytes) [00000000000000000000000000000000]
21381 ms <    +0 ms>:APP NONCE AB     (16  bytes) [8649f86a4859d4877d43911464c0be6d]
21381 ms <    +0 ms>:CODEC TX         (5   bytes) [0b00aec6c0]
```
I'm so sorry ..   ASM is a mess ; ))

**Comment by dev-zzo** [comment]
Oh, I see. The routine doesn't work correctly since it requires the previous ciphertext block to be intact, but in our case it is overwritten as our source and destination buffers are the same. Need to think how to work around that.

**Comment by dev-zzo** [comment]
I have just pushed commit f0f8619, which hopefully fixes this once and for all. xD Some performance penalty is taken when buffers are overlapping, but I don't think this can be avoided in such a case. Reference code seems to assume the buffers are different ans has the same issue if they are not.

**Comment by dev-zzo** [comment]
And yeah, this has nothing to do with assembly -- I doubt I could notice this faster if it were in C. Not having an ICE debugger, though, makes things really hard...

**Comment by shombre** [comment]
wasn't my purpose to talk bad about assembly, I am just to lazy to dig into it.. ; )

good news:
```
38945 ms < +3638 ms>:CODEC RX         (6   bytes) [0a000a00de77]
38945 ms <    +0 ms>:APP AUTH KEY     (16  bytes) [00000000000000000000000000000000]
38945 ms <    +0 ms>:APP NONCE B      (8   bytes) [cafebabe00112233]
38946 ms <    +1 ms>:CODEC TX         (13  bytes) [0a00afee91301ee8f584d6dec0]
38953 ms <    +7 ms>:CODEC RX         (21  bytes) [0b00aff9093f4c6f5388598a058438d17635fd0897]
38953 ms <    +0 ms>:APP AUTH KEY     (16  bytes) [00000000000000000000000000000000]
38953 ms <    +0 ms>:APP NONCE AB     (16  bytes) [0ae6b0a204ea57c0febabe00112233ca]
38953 ms <    +0 ms>:CODEC TX         (13  bytes) [0b000075a97312079d5e390b0e]
```
```
55469 ms <+12785 ms>:CODEC RX         (6   bytes) [0a000a00de77]
55469 ms <    +0 ms>:APP AUTH KEY     (16  bytes) [11111111111111111111111111111111]
55469 ms <    +0 ms>:APP NONCE B      (8   bytes) [cafebabe00112233]
55469 ms <    +0 ms>:CODEC TX         (13  bytes) [0a00afc884f86a75717356f88f]
55483 ms <   +14 ms>:CODEC RX         (21  bytes) [0b00afab3732967a43082eaa76fda36d0e8a16c48e]
55483 ms <    +0 ms>:APP AUTH KEY     (16  bytes) [11111111111111111111111111111111]
55483 ms <    +0 ms>:APP NONCE AB     (16  bytes) [e6c86d91803a825efebabe00112233ca]
55483 ms <    +0 ms>:CODEC TX         (13  bytes) [0b0000161baabfc6805c6c26ad]
```
```
42745 ms < +7271 ms>:CODEC RX         (6   bytes) [0a000a00de77]
42745 ms <    +0 ms>:APP AUTH KEY     (16  bytes) [11111111111111112211111111111111]
42745 ms <    +0 ms>:APP NONCE B      (8   bytes) [cafebabe00112233]
42745 ms <    +0 ms>:CODEC TX         (13  bytes) [0a00af1cd3c4c3605705eb7026]
42753 ms <    +8 ms>:CODEC RX         (21  bytes) [0b00af28b1f3da75c05610373248ff4b483069506f]
42753 ms <    +0 ms>:APP AUTH KEY     (16  bytes) [11111111111111112211111111111111]
42753 ms <    +0 ms>:APP NONCE AB     (16  bytes) [be402b754da5d2edfebabe00112233ca]
42753 ms <    +0 ms>:CODEC TX         (13  bytes) [0b000030ade08c652b653b3e0a]
```
The reader told me `authentication succesfull` in all three cases! 
Sessionkey looks good as well! * **thumb up** *

**Comment by dev-zzo** [comment]
woop woop woop (v) (o,,,o) (v)
closing the issue, then. :-) thanks again for all your help!
