### ISSUE TITLE
desfire: card structure / app properties

### ISSUE THREAD

**Issue by shombre** [dev-zzo/ChameleonMini#8]
Are app properties intended to work already?
When I `CreateApplication` with i.e. `KeySettings = 0x0E` / `KeyCount = 0x02`, then `SelectApplication` and `GetKeySettings`, the returned values are not as expected, i.e. `KeySettings = 0x7F` / `KeyCount = 0x33`.

**Comment by dev-zzo** [comment]
As for the app props -- they should be working as intended, at least, no active development is planned for that in the nearest future.

**Comment by dev-zzo** [comment]
Also in case of on-card related issues, you can always dump the card contents via `DOWNLOAD` and share with us for further debugging. The complete non-volatile state is downloadable.

**Comment by shombre** [comment]
> This should be fixed in commit 98be118. Please see if that's the case.

it's working now as intended!

also c89c970ff916a680f70085ff7cbd47b142b46db3 helps a lot to understand the card structure without diggin to deep! * **thumb up** *
