### ISSUE TITLE
ISO14443-4 deselect

### ISSUE THREAD

**Issue by geo-rg** [dev-zzo/ChameleonMini#9]
I just looked over the desfire emulation code for the first time - very nice!

I think I found one bug: In uint16_t ISO144434ProcessBlock(uint8_t*,uint16_t) the card does not answer to an S(DESELECT) message, but the standard states that the PICCs indicates that the deselection was successful by answering with an S(DESELECT) message.

**Comment by dev-zzo** [comment]
That might be the case; I've never got to test that. :-) Care to submit a patch?

**Comment by dev-zzo** [comment]
Fixed with commit 44ee4f6. Thanks for reporting!
